apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-service
  template:
    metadata:
      labels:
        app: simple-service
    spec:
      containers:
      - name: simple-service
        image: gcr.io/testproject-453400/simple-service:latest
        ports:
        - containerPort: 8089
        resources:
          requests:
            memory: "150Mi"   # Minimum memory required
            cpu: "150m"       # Minimum CPU required (0.25 CPU)
          limits:
            memory: "512Mi"   # Maximum memory allowed
            cpu: "500m"       # Maximum CPU allowed (0.5 CPU)
