apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: simple-service-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: simple-service  # Make sure this matches your deployment name
  minReplicas: 2
  maxReplicas: 8
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 30  # Scale when CPU exceeds 50%
